spring:
  data:
    redis:
      password: ${REDIS_PASSWORD:ingotredis}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST1:ingot-nacos}:${NACOS_PORT1:8848},${NACOS_HOST2:ingot-nacos}:${NACOS_PORT2:8849},${NACOS_HOST3:ingot-nacos}:${NACOS_PORT3:8850}
        namespace: ingot
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        group: DEV_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}
        group: DEV_GROUP
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml

springdoc:
  api-docs:
    enabled: true

logs:
  path: /ingot-data/logs

# 日志等级
logging:
  level:
    org.springframework.web: trace
    com.alibaba.nacos.client.naming: info