spring:
  datasource:
    username: ${MYSQL_USERNAME}  # 生产环境必须配置
    password: ${MYSQL_PASSWORD}  # 生产环境必须配置
  data:
    redis:
      password: ${REDIS_PASSWORD}  # 生产环境必须配置
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}  # 生产环境必须配置
      username: ${NACOS_USERNAME}  # 生产环境必须配置
      password: ${NACOS_PASSWORD}  # 生产环境必须配置
      discovery:
        namespace: ${NACOS_NAMESPACE:ingot}
        group: ${NACOS_GROUP:PROD_GROUP}
      config:
        namespace: ${NACOS_NAMESPACE:ingot}
        group: ${NACOS_GROUP:PROD_GROUP}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:application-mysql.yml
      - optional:nacos:${spring.application.name}.yml?refreshEnabled=true