# ====================================
# MySQL & Redis
# ====================================

services:
  # ========== MySQL 服务 ==========
  mysql-db:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION:-8.0.44}
    restart: always
    networks:
      - extnet
    ports:
      - target: 3306
        published: ${MYSQL_PORT:-3306}
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WORK_DIR}/mysql/data:/var/lib/mysql
      - ${WORK_DIR}/mysql/init:/docker-entrypoint-initdb.d

  # ========== Redis 服务 ==========
  redis:
    image: ${REDIS_IMAGE}:${REDIS_VERSION:-8.2.0}
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf", "--appendonly", "yes"]
    networks:
      - extnet
    ports:
      - target: 6379
        published: ${REDIS_PORT:-6379}
    volumes:
      - ${WORK_DIR}/redis/data:/data
      - ${WORK_DIR}/redis/conf/redis.conf:/etc/redis/redis.conf

  # ========== Minio 服务 ==========
  minio:
    image: ${MINIO_IMAGE}:${MINIO_VERSION}
    restart: always
    command: ["server", "/data", "--console-address", ':5001', '-address', ':9000']
    networks:
      - extnet
    ports:
      - target: 5001
        published: ${MINIO_CONSOLE_PORT:-5001}
      - target: 9000
        published: ${MINIO_API_PORT:-9000}
    volumes:
      - ${WORK_DIR}/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  # ========== Nacos 服务 ==========
  nacos:
    image: ${NACOS_IMAGE}:${NACOS_VERSION}
    restart: always
    networks:
      - extnet
    ports:
      - target: 8080
        published: ${NACOS_CONSOLE_PORT:-8181}
      - target: 8848
        published: ${NACOS_SERVER_PORT:-8848}
      - target: 9848
        published: ${NACOS_GRPC_CLIENT_PORT:-9848}
      - target: 9849
        published: ${NACOS_GRPC_SERVER_PORT:-9849}
    volumes:
      - ${WORK_DIR}/nacos/logs:/home/nacos/logs
    environment:
      - NACOS_SERVER_PORT=${NACOS_SERVER_PORT}
    env_file:
      - nacos/standalone.env

# ========== 网络配置 ==========
networks:
  extnet:
    name: ${DOCKER_NETWORK}
    external: true